### ISSUE TITLE
Intermittent javascript test loading error on travis

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/crates.io#1137]
I have no idea why this is happening, and why it's happening intermittently, and why it's only happening on travis. I've tried searching for the error and couldn't find anything that looked relevant, I really could use some help from someone with more JS experience than me :(

The error happens when travis runs `npm test`:

```
$ npm test

> cargo@0.0.0 test /home/travis/build/rust-lang/crates.io

> ember test

Could not start watchman

Visit https://ember-cli.com/user-guide/#watchman for more info.

Building

Cannot find module 'faker/package.json' from '/home/travis/build/rust-lang/crates.io/node_modules/ember-cli-mirage'

Error: Cannot find module 'faker/package.json' from '/home/travis/build/rust-lang/crates.io/node_modules/ember-cli-mirage'

    at Function.module.exports [as sync] (/home/travis/build/rust-lang/crates.io/node_modules/resolve/lib/sync.js:40:15)

    at npmTree (/home/travis/build/rust-lang/crates.io/node_modules/ember-cli-node-assets/index.js:132:35)

    at /home/travis/build/rust-lang/crates.io/node_modules/ember-cli-node-assets/index.js:120:16

    at Array.map (native)

    at collectModuleTrees (/home/travis/build/rust-lang/crates.io/node_modules/ember-cli-node-assets/index.js:119:6)

    at treeFor (/home/travis/build/rust-lang/crates.io/node_modules/ember-cli-node-assets/index.js:108:15)

    at Class.treeForVendor (/home/travis/build/rust-lang/crates.io/node_modules/ember-cli-node-assets/index.js:32:12)

    at Class._treeFor (/home/travis/build/rust-lang/crates.io/node_modules/ember-cli/lib/models/addon.js:556:33)

    at Class.treeFor (/home/travis/build/rust-lang/crates.io/node_modules/ember-cli/lib/models/addon.js:516:21)

    at addons.reduce (/home/travis/build/rust-lang/crates.io/node_modules/ember-cli/lib/models/addon.js:383:26)

The command "npm test" exited with 1.
```

Faker is definitely there, and rerunning a job that fails in this way usually passes.

**Comment by Turbo87** [comment]
@carols10cents is this still an issue? Haven't noticed any such issues in the past few weeks :thinking:

**Comment by kzys** [comment]
I agree we can resolve this issue. Our build seems fine these days. https://travis-ci.com/rust-lang/crates.io/builds
