### ISSUE TITLE
Sometimes I see this: "Cannot read property 'some' of undefined"

### ISSUE THREAD

**Issue by im-0** [rust-lang/crates.io#1405]
```
    TypeError: Cannot read property 'some' of undefined
    at store.find.catch.t (https://crates.io/assets/cargo-3925b0e0c2a6ade99d7a65b3a18503b9.js:296:110)
    at c (https://crates.io/assets/vendor-9bb8d18a891779d4f9bdd45cb792d166.js:3626:25)
    at b (https://crates.io/assets/vendor-9bb8d18a891779d4f9bdd45cb792d166.js:3634:9)
    at v (https://crates.io/assets/vendor-9bb8d18a891779d4f9bdd45cb792d166.js:3632:43)
    at f (https://crates.io/assets/vendor-9bb8d18a891779d4f9bdd45cb792d166.js:3629:120)
    at e.invoke (https://crates.io/assets/vendor-9bb8d18a891779d4f9bdd45cb792d166.js:1577:145)
    at e.flush (https://crates.io/assets/vendor-9bb8d18a891779d4f9bdd45cb792d166.js:1564:172)
    at e.flush (https://crates.io/assets/vendor-9bb8d18a891779d4f9bdd45cb792d166.js:1580:15)
    at e.end (https://crates.io/assets/vendor-9bb8d18a891779d4f9bdd45cb792d166.js:1588:9)
    at _boundAutorunEnd (https://crates.io/assets/vendor-9bb8d18a891779d4f9bdd45cb792d166.js:1584:388)
```

When trying to open crate page (https://crates.io/crates/log4rs-syslog for example). Reloading page usually solves this.

**Comment by jtgeibel** [comment]
Given the backtrace, I'm guessing the error is originating from one of the following 3 places:

```cmd
$ git grep store.find
app/routes/category.js:        return this.store.find('category', params.category_id).catch(e => {
app/routes/crate.js:        return this.store.find('crate', params.crate_id).catch(e => {
app/routes/keyword.js:        return this.store.find('keyword', keyword_id).catch(e => {
```

For this URL it is the crate route, but after all 3 of those results is:

```js
if (e.errors.some(e => e.detail === 'Not Found')) {
```

It appears that `e.errors` is undefined for some reason.  It would be really helpful to know the specific response and status code that you're seeing when this occurs, but it may be difficult to catch this while the network console is open.

If I go to the URL for a crate that doesn't exist (https://crates.io/crates/nonexistent) then I see the expected error message.  In this scenario, the request to the backend returns a 404 with the contents `{"errors":[{"detail":"Not Found"}]}` and the error handling works as expected.

Given that backend errors don't always result in a JSON message of this format, we should probably fall back to displaying the response as plain text if `e.errors` is undefined.  The response may include the request_id or other useful information for tracking this down in the logs.

**Comment by locks** [comment]
I am closing this issue as I still haven't been able to reproduce. Please do re-open if you have a reproduction!
