### ISSUE TITLE
localStorage are now required

### ISSUE THREAD

**Issue by danielzgtg** [rust-lang/crates.io#2502]
crates.io did not require cookies to be enabled a while ago. Now it does.

As it was working before, there is no technical reason for cookies. This breaks the website for people who have cookies turned off. I would prefer to leave cookies off for as many websites as possible for privacy reasons.

The following error appears in Chrome DevTools Console:
```
cargo-7b7736ac987e50efa6c519074468e5de.js:489 Uncaught (in promise) DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at l.initializer (https://crates.io/assets/cargo-7b7736ac987e50efa6c519074468e5de.js:489:608)
    at l.get [as useNewDesign] (https://crates.io/assets/vendor-44923026bc511b3f688e1e11fe194280.js:1177:34)
    at xe (https://crates.io/assets/vendor-44923026bc511b3f688e1e11fe194280.js:1238:45)
    at https://crates.io/assets/vendor-44923026bc511b3f688e1e11fe194280.js:619:83
    at X (https://crates.io/assets/vendor-44923026bc511b3f688e1e11fe194280.js:1181:5)
    at $.compute (https://crates.io/assets/vendor-44923026bc511b3f688e1e11fe194280.js:619:67)
    at $.value (https://crates.io/assets/vendor-44923026bc511b3f688e1e11fe194280.js:612:62)
    at G.value (https://crates.io/assets/vendor-44923026bc511b3f688e1e11fe194280.js:2735:90)
    at e.ReferenceCache.initialize (https://crates.io/assets/vendor-44923026bc511b3f688e1e11fe194280.js:2687:91)
    at e.ReferenceCache.peek (https://crates.io/assets/vendor-44923026bc511b3f688e1e11fe194280.js:2682:206)
```

**Comment by Turbo87** [comment]
thanks for reporting this. it is indeed not technically necessary unless you want to authenticate. it seems that we regressed in this regard.

**Comment by jtgeibel** [comment]
I've changed the title to reference localStorage instead of cookies. We just need to wrap access to localStorage in a try/catch block, where we ignore the error or provide a default value. The only non-test code I see missing this is in `app/services/design.js`.
