### ISSUE TITLE
meta: Deprecation warning reported from vendored JS

### ISSUE THREAD

**Issue by camelid** [rust-lang/crates.io#3390]
When I run `yarn test` I get dozens or hundreds of copies of the same deprecation warning that fills my terminal and makes it very hard to find what I'm looking for when looking through the output:

```
            WARN: DEPRECATION: Importing htmlSafe from '@ember/string' is deprecated. Please import htmlSafe from '@ember/template' instead. [deprecation id: ember-string.htmlsafe-ishtmlsafe] See https://deprecations.emberjs.com/v3.x/#toc_ember-string-htmlsafe-ishtmlsafe for more details.
                    at logDeprecationStackTrace (http://localhost:7357/assets/vendor.js:34410:21)
                    at HANDLERS.<computed> (http://localhost:7357/assets/vendor.js:34543:9)
                    at raiseOnDeprecation (http://localhost:7357/assets/vendor.js:34437:9)
                    at HANDLERS.<computed> (http://localhost:7357/assets/vendor.js:34543:9)
                    at invoke (http://localhost:7357/assets/vendor.js:34555:9)
                    at deprecate (http://localhost:7357/assets/vendor.js:34511:28)
                    at deprecateImportFromString (http://localhost:7357/assets/vendor.js:60446:51)
                    at Object.get [as htmlSafe] (http://localhost:7357/assets/vendor.js:60462:7)
                    at makeSvg (http://localhost:7357/assets/vendor.js:113176:25)
```

Every usage of `htmlSafe` in the crates.io source looks correct:

```
app/helpers/format-email.js
2:import { htmlSafe } from '@ember/template';
17:  return htmlSafe(ret);

app/helpers/html-safe.js
2:import { htmlSafe as markAsSafe } from '@ember/template';
4:export function htmlSafe([content] /*, hash*/) {
8:export default helper(htmlSafe);

app/services/progress.js
2:import { htmlSafe } from '@ember/template';
17:    return htmlSafe(this._style);
```

The combination of that and the stack trace showing `/assets/vendor.js` makes me think this is coming from a dependency.

Interestingly, I don't see this deprecation warning in the CI logs.

Also, running `yarn install` doesn't fix it.

**Comment by Turbo87** [comment]
https://github.com/rust-lang/crates.io/pull/3379 includes https://github.com/rust-lang/crates.io/pull/3379, which should have fixed this problem. can you make sure that you're on the latest `master` and have rebased your branches? :)
