### ISSUE TITLE
Unable to build crates.io on Windows

### ISSUE THREAD

**Issue by Sebi2020** [rust-lang/crates.io#3818]
The build failes with the following error:

Short version:
```
  --- stderr
  thread 'main' panicked at 'failed to execute command: Das System kann die angegebene Datei nicht finden. (os error 2)', C:\Users\anonymous\.cargo\registry\src\github.com-1ecc6299db9ec823\jemalloc-sys-0.3.2\build.rs:389:19
````

Long version:
```
warning: "jemalloc support for `x86_64-pc-windows-msvc` is untested"

error: failed to run custom build command for `jemalloc-sys v0.3.2`

Caused by:
  process didn't exit successfully: `C:\Users\anonymous\Desktop\crates.io\target\debug\build\jemalloc-sys-0c5391c9fd782756\build-script-build` (exit code: 101)
  --- stdout
  TARGET=x86_64-pc-windows-msvc
  HOST=x86_64-pc-windows-msvc
  NUM_JOBS=8
  OUT_DIR="C:\\Users\\anonymous\\Desktop\\crates.io\\target\\debug\\build\\jemalloc-sys-486aee36f8aadca5\\out"
  BUILD_DIR="C:\\Users\\anonymous\\Desktop\\crates.io\\target\\debug\\build\\jemalloc-sys-486aee36f8aadca5\\out\\build"
  SRC_DIR="C:\\Users\\anonymous\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\jemalloc-sys-0.3.2"
  cargo:warning="jemalloc support for `x86_64-pc-windows-msvc` is untested"
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-pc-windows-msvc")
  HOST = Some("x86_64-pc-windows-msvc")
  CC_x86_64-pc-windows-msvc = None
  CC_x86_64_pc_windows_msvc = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-pc-windows-msvc = None
  CFLAGS_x86_64_pc_windows_msvc = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  DEBUG = Some("true")
  CC="C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\VC\\Tools\\MSVC\\14.13.26128\\bin\\HostX64\\x64\\cl.exe"
  CFLAGS="-nologo -MD -Z7 -Brepro -W4"
  JEMALLOC_REPO_DIR="jemalloc"
  JEMALLOC_SRC_DIR="C:\\Users\\anonymous\\Desktop\\crates.io\\target\\debug\\build\\jemalloc-sys-486aee36f8aadca5\\out\\jemalloc"
  CARGO_FEATURE_PROFILING set
  running: "sh" "/c/Users/anonymous/Desktop/crates.io/target/debug/build/jemalloc-sys-486aee36f8aadca5/out/jemalloc/configure" "--disable-cxx" "--with-private-namespace=_rjem_" "--enable-prof" "--host=x86_64-pc-win32" "--build=x86_64-pc-win32" "--prefix=C:\\Users\\anonymous\\Desktop\\crates.io\\target\\debug\\build\\jemalloc-sys-486aee36f8aadca5\\out"

  --- stderr
  thread 'main' panicked at 'failed to execute command: Das System kann die angegebene Datei nicht finden. (os error 2)', C:\Users\anonymous\.cargo\registry\src\github.com-1ecc6299db9ec823\jemalloc-sys-0.3.2\build.rs:389:19
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...a
```

**Comment by Turbo87** [comment]
Our primary target is Linux since that is what runs our service in production. Some people also use MacOS for development since it is reasonably close to Linux. Supporting Windows is out of scope for this project due to the additional maintenance effort required. We are open to merging PRs that improve the development experience on Windows, but we are unlikely to add a CI job that enforces Windows support.

(see also https://github.com/rust-lang/crates.io/issues/930#issuecomment-710091739)
