### ISSUE TITLE
e.get is not a function

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/crates.io#428]
https://crates.io/crates/bert

![selection_005](https://cloud.githubusercontent.com/assets/1940490/18186267/c005479e-7056-11e6-8c75-fdc2ed23ebb5.png)

The stacktrace is:

```
  e.default<.setHeadTags@https://crates.io/assets/cargo-c12b1b6520f9d4295083e8d167bc0625.js:1:29205
e.default<.afterModel@https://crates.io/assets/cargo-c12b1b6520f9d4295083e8d167bc0625.js:1:29077
p@https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:18:15207
n.prototype.runSharedModelHook@https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:17:26529
n.prototype.runAfterModelHook@https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:17:26238
a/<@https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:18:13872
g@https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:18:18908
b@https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:18:19003
v@https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:18:18811
@https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:13:16139
r.prototype.invoke@https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:5:31351
r.prototype.flush@https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:5:31885
n.prototype.flush@https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:5:29941
a.prototype.end@https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:5:23207
a.prototype.run@https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:5:24343
a.prototype.join@https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:5:24405
u.join@https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:11:3073
d<.ajax/</c.error@https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:24:15587
ie.Callbacks/c@https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:3:26369
ie.Callbacks/d.fireWith@https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:3:27191
r@https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:5:9124
.send/t@https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:5:15309
```

**Comment by dtolnay** [comment]
The previous one is from Firefox. In Chrome:

![selection_006](https://cloud.githubusercontent.com/assets/1940490/18186316/03b58f62-7057-11e6-9002-4b583a065aa3.png)

```

  TypeError: e.get is not a function
    at r.setHeadTags (https://crates.io/assets/cargo-c12b1b6520f9d4295083e8d167bc0625.js:1:29207)
    at r.afterModel (https://crates.io/assets/cargo-c12b1b6520f9d4295083e8d167bc0625.js:1:29082)
    at Object.p [as applyHook] (https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:18:15212)
    at Object.runSharedModelHook (https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:17:26531)
    at Object.runAfterModelHook (https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:17:26243)
    at https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:18:13874
    at g (https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:18:18908)
    at b (https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:18:19003)
    at v (https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:18:18811)
    at https://crates.io/assets/vendor-211b6ccdc7882f9afdd3922ed76fbd35.js:13:16139
```

**Comment by steveklabnik** [comment]
Does this only happen on the pages of packages that don't exist?

**Comment by dtolnay** [comment]
It seems so.

**Comment by alexcrichton** [comment]
cc @rjgoldsborough 

perhaps related to https://github.com/rust-lang/crates.io/pull/421?

**Comment by rjgoldsborough** [comment]
I *think* it might be this line or related to the afterModel stuff here.
https://github.com/rust-lang/crates.io/blob/master/app/routes/crate.js#L22

The model returns an error when a crate is not found so model.get('description') would fail I believe.

**Comment by rjgoldsborough** [comment]
yeah, that looks to be the case. removing https://github.com/rust-lang/crates.io/blob/master/app/routes/crate.js#L13 fixes the error it seems.

**Comment by rjgoldsborough** [comment]
I think that PR will fix it but would love someone else to confirm. Just checks to make sure model.get is actually a function and model isn't just the error from the above failed promise.

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang/crates.io/pull/429

Thanks @rjgoldsborough!
