### ISSUE TITLE
I can't Log in(Cry with joy)

### ISSUE THREAD

**Issue by 3442853561** [rust-lang/crates.io#454]
Something Went Wrong!
Calling delete on 'github_response' is not allowed in strict mode

**Comment by 3442853561** [comment]
Can log in China?

**Comment by alexcrichton** [comment]
This looks like it may be a JS error? Would it be possible to perhaps get a backtrace in the JS console to see what went wrong?

**Comment by 3442853561** [comment]
@alexcrichton 
TypeError: Calling delete on 'github_response' is not allowed in strict mode
   at beforeModel (https://crates.io/assets/cargo-a05cec2b6a938507114be70cadbeb0df.js:2:2740)
   at p (https://crates.io/assets/vendor-6df1fe7de575148b987cb217b02e72e6.js:18:15648)
   at n.prototype.runSharedModelHook (https://crates.io/assets/vendor-6df1fe7de575148b987cb217b02e72e6.js:17:27032)
   at n.prototype.runBeforeModelHook (https://crates.io/assets/vendor-6df1fe7de575148b987cb217b02e72e6.js:17:26552)
   at Anonymous function (https://crates.io/assets/vendor-6df1fe7de575148b987cb217b02e72e6.js:18:14373)
   at g (https://crates.io/assets/vendor-6df1fe7de575148b987cb217b02e72e6.js:18:19419)
   at b (https://crates.io/assets/vendor-6df1fe7de575148b987cb217b02e72e6.js:18:19516)
   at v (https://crates.io/assets/vendor-6df1fe7de575148b987cb217b02e72e6.js:18:19329)
   at Anonymous function (https://crates.io/assets/vendor-6df1fe7de575148b987cb217b02e72e6.js:13:16694)
   at r.prototype.invoke (https://crates.io/assets/vendor-6df1fe7de575148b987cb217b02e72e6.js:5:31852)
