### ISSUE TITLE
Reserved Crate Names Do Not Load: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by sunjay** [rust-lang/crates.io#877]
This bug occurs when you visit: 
* https://crates.io/crates/rustc
* https://crates.io/crates/crates.io
* and any other [reserved crate name](https://github.com/rust-lang/crates.io/blob/b0a7a8d2f4356f38145cbbb05715ed0eedb136ce/migrations/20170305095748_create_reserved_crate_names/up.sql)

![screenshot from 2017-07-11 11-07-16](https://user-images.githubusercontent.com/530939/28075396-5cf19b7a-6629-11e7-9b36-71784c2b5a63.png)

Full error:

```
TypeError: Cannot read property 'get' of undefined
    at afterModel (https://crates.io/assets/cargo-94f48e99a5d854f990de61139974b13b.js:210:248)
    at v (https://crates.io/assets/vendor-e7c706a5c4002b19afc2599829efbbbc.js:3783:88)
    at runSharedModelHook (https://crates.io/assets/vendor-e7c706a5c4002b19afc2599829efbbbc.js:3857:7)
    at runAfterModelHook (https://crates.io/assets/vendor-e7c706a5c4002b19afc2599829efbbbc.js:3856:42)
    at https://crates.io/assets/vendor-e7c706a5c4002b19afc2599829efbbbc.js:3766:20
    at R (https://crates.io/assets/vendor-e7c706a5c4002b19afc2599829efbbbc.js:3934:82)
    at S (https://crates.io/assets/vendor-e7c706a5c4002b19afc2599829efbbbc.js:3935:12)
    at k (https://crates.io/assets/vendor-e7c706a5c4002b19afc2599829efbbbc.js:3933:144)
    at invokeWithOnError (https://crates.io/assets/vendor-e7c706a5c4002b19afc2599829efbbbc.js:1441:242)
    at s.flush (https://crates.io/assets/vendor-e7c706a5c4002b19afc2599829efbbbc.js:1446:74)
```

**Comment by ashleygwilliams** [comment]
hey @sunjay thanks for reporting this! i'm gonna take a stab at solving it today and will let you know the status update when i have one!

**Comment by Deedasmi** [comment]
Was this fixed? Can't reproduce.

**Comment by sgrif** [comment]
Yes it was.
