### ISSUE TITLE
Something Went Wrong! Crate 'webgl' does not exist

### ISSUE THREAD

**Issue by fst3a** [rust-lang/crates.io#880]
Gee, I accidentally typed in some random letters and this happened.

https://crates.io/crates/webgl

```
Cannot read property 'get' of undefined

  TypeError: Cannot read property 'get' of undefined
    at afterModel (https://crates.io/assets/cargo-50b635d9a1285b28fd6968f81fa1835e.js:210:248)
    at v (https://crates.io/assets/vendor-e7c706a5c4002b19afc2599829efbbbc.js:3783:88)
    at runSharedModelHook (https://crates.io/assets/vendor-e7c706a5c4002b19afc2599829efbbbc.js:3857:7)
    at runAfterModelHook (https://crates.io/assets/vendor-e7c706a5c4002b19afc2599829efbbbc.js:3856:42)
    at https://crates.io/assets/vendor-e7c706a5c4002b19afc2599829efbbbc.js:3766:20
    at R (https://crates.io/assets/vendor-e7c706a5c4002b19afc2599829efbbbc.js:3934:82)
    at S (https://crates.io/assets/vendor-e7c706a5c4002b19afc2599829efbbbc.js:3935:12)
    at k (https://crates.io/assets/vendor-e7c706a5c4002b19afc2599829efbbbc.js:3933:144)
    at invokeWithOnError (https://crates.io/assets/vendor-e7c706a5c4002b19afc2599829efbbbc.js:1441:242)
    at s.flush (https://crates.io/assets/vendor-e7c706a5c4002b19afc2599829efbbbc.js:1446:74)
```
![image](https://user-images.githubusercontent.com/25141408/28093380-b0a94382-669f-11e7-9670-be604b480cf7.png)

**Comment by fst3a** [comment]
Oh, it seems it has already been reported https://github.com/rust-lang/crates.io/issues/877
